sudo: required 
language: genric
services:
    -docker

before_install:
    - docker build  -t kiarifulla/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kiarifulla/docker-react npm run test

deploy:
    provider: elasticbeanstalk 
    region: "ap-south-1"
    app: "docker-react"
    environment: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-029719392277"
    bucket_path: "docker-react"
    on:
        branch: master